### PR TITLE
Update open-balena-base to 12.0.3

### PR DESCRIPTION
**Pull request by ab77**
* resolve VPN_SERVICE_ADDRESS via a promise
* log ipAddress during service registration
* use auto-resolved Sentry DSN is present

Update open-balena-base from 12.0.2 to 12.1.0

Change-type: minor

### CODE REVIEW

**Comment by ab77** [comment]
@Page- @dfunckt @pranavpeshwe can you please review my changes, I've tested locally in my bob and they appear to work reliably.

**Comment by pranavpeshwe** [comment]
@ab77 Went through the code and don't see anything obvious that should break things. Having said that, I've never encountered this issue myself. Do you run into this problem every single time or only some times?

**Comment by ab77** [comment]
> @ab77 Went through the code and don't see anything obvious that should break things. Having said that, I've never encountered this issue myself. Do you run into this problem every single time or only some times?

it usually happens on the first start of the VPN container, a subsequent restart fixes it.

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci I self-certify!

**Pull request merged**
