### PR TITLE
versionbot: add structured CHANGELOG.yml

### PR DESCRIPTION
**Pull request by wrboyce**
Change-type: patch
Signed-off-by: Will Boyce \<will@balena.io\>

---
##### Contributor checklist

- [ ] Build output has been rebuilt and tested
- [ ] Introduces security considerations
- [ ] Tests are included
- [ ] Documentation is added or changed
- [ ] Affects the development, build or deployment processes of the component

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by wrboyce** [comment]
@hedss the _initial_ changelog needs generating (or `touch`-ing if you don't care about a history). I knocked [this script](https://gist.github.com/wrboyce/1fec6233a89521da6220d3a9eacef5ed) together for retrospectively generating the structured changelog.

**Comment by wrboyce** [comment]
@hedss damn, not out of date, you've found a bug in my script!

I'm currently doing this to order the versions for the changelog:

```bash
mapfile -t versions < <(sort -nr <(printf "%s\n" "${tmp}"/v*.yml))
```

Which seems to puts 8.10.x between 8.1.x and 8.2.x. Annoying.

**Comment by hedss** [comment]
@wrboyce The joys of lexicographical sorts. ;-) And I'm lifting your script wholesale, btw!

**Comment by wrboyce** [comment]
Manually moved the erroneous entries to the top of the changelog.

**Comment by wrboyce** [comment]
Please do! I think @nazrhom was interested in including it in a proper repo somewhere.

**Comment by hedss** [comment]
@wrboyce @nazrhom Yep, I'd be very keen that this gets VBd properly, too. With a semver sorting fix. ;-)

**Comment by nazrhom** [comment]
@resin-ci retest

**Pull request merged**
